# Rade相关配置
rade:
  # 缓存名称
  cacheName: comm
  plugin:
    # 插件安装位置
    path: assets/plugin
  # token 相关配置
  token:
    # 过期时间 单位：秒 半小时
    expire: 1800
    # 刷新token过期时间 单位：秒 7天
    refreshExpire: 604800
  # 文件上传相关
  file:
    #上传模式
    mode: local
    # 本地上传配置
    local:
      # 文件访问地址
      base-url: http://127.0.0.1:${server.port}/upload
  # 系统日志请求参数超过1024字节 就不记录,避免日志过大
  log:
    # 请求参数最大字节,超过请求参数不记录
    max-byte-length: 1024
    # 核心线程数的倍数
    core-pool-size-multiplier: 2
    # 最大线程数的倍数
    max-pool-size-multiplier: 3
    # 队列容量的倍数
    queue-capacity-multiplier: 3


  # 认证授权忽略url
  aac:
    login:
      type: single
      loginUrl: /v1/api/aac/login
    #忽略后台鉴权url
    whitelist:
      - /
      - /upload/**
      - /actuator/**
      - /download/**
      - /static/**
      - /favicon.ico
      - /v3/api-docs/**
      - /swagger
      - /swagger-ui/**
      - /css/*
      - /js/*
      - /druid/**
      - /admin/base/open/**
      - /v1/api/aac/login/enable
      - /v1/api/aac/captcha
      - /v1/api/aac/login
      - /v1/api/aac/logout
      - /swagger-ui/**
      - /webjars/**
      - /templates/**
      - /doc
      - /api-docs/**
      #- /favicon.ico
      - /ws
    jwt-setting:
      # 令牌自定义标识
      header: Authorization
      # 令牌密钥
      secret-key: Yx7GcP3UY194v8U.fLyhBiFZFxKOagQZt1baEhKlTfMW
      # 令牌过期时间
      expiration: 86400000 # a day
      # 刷新令牌过期时间
      refresh-expiration: 604800000 # 7 days
    # 忽略后台鉴权url
    adminAuthUrls:
      - /
      - /upload/**
      - /actuator/**
      - /download/**
      - /static/**
      - /favicon.ico
      - /v3/api-docs/**
      - /swagger
      - /swagger-ui/**
      - /css/*
      - /js/*
      - /druid/**
      - /admin/base/open/**
     # - /favicon.ico
    # 忽略记录请求日志url
    logUrls:
      - /
      - /**/aid
      - /app/**
      - /css/*
      - /js/*
      #- /favicon.ico

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
# Rade相关配置
rade:
  initializer:
    # 初始化数据
    initData: true
    dataDir: file://E:\\workspaces\\java\\projects\\dows\\dows-rade\\rade-app\\src\\main\\resources\\rade\\data\\db
    menuDir: file://E:\\workspaces\\java\\projects\\dows\\dows-rade\\rade-app\\src\\main\\resources\\rade\\data\\menu


---
#开发环境
spring:
  config:
    activate:
      on-profile: prd
# AutoTable配置，根据实体类自动生成表
auto-table:
  # 启用自动维护表功能
  enable: false
