spring:
  # caffeine 缓存
  cache:
    type: caffeine
    file: assets/cache

  #redis 缓存
  #  cache:
  #    type: redis
  #  data:
  #    redis:
  #      host: 127.0.0.1
  #      port: 6379
  #      database: 0
  #      password:

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev


---
#开发环境
spring:
  config:
    activate:
      on-profile: prd
