## 文档
#springdoc:
#  api-docs:
#    #swagger后端请求地址
#    path: /v3/api-docs
#  swagger-ui:
#    #自定义swagger前端请求路径，输入http://127.0.0.1:端口号/swagger会自动重定向到swagger页面
#    path: /swagger
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
#  group-configs:
#    - group: admin
#      paths-to-match: '/**'
#      packages-to-scan: org.dows.modules.*.*.admin
#    - group: tenant
#      paths-to-match: '/**'
#      packages-to-scan: org.dows.modules.*.*.tenant
#    - group: user
#      paths-to-match: '/**'
#      packages-to-scan: org.dows.modules.*.*.user
#    - group: app
#      paths-to-match: '/**'
#      packages-to-scan: org.dows.modules.*.*.app
#    - group: open
#      paths-to-match: '/**'
#      packages-to-scan: org.dows.modules.*.*.open
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-group: true




---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
# 文档
springdoc:
  api-docs:
    #是否开启文档功能 本地为了配合aid功能不可关闭
    enabled: true

---
#开发环境
spring:
  config:
    activate:
      on-profile: prd
# 文档
springdoc:
  api-docs:
    #是否开启文档功能 本地为了配合aid功能不可关闭
    enabled: false