server:
  port: 8090
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 32

spring:
  main:
#    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: rade-admin
  profiles:
    include: apidoc,mybatis,mysql,quartz,rade,cache
    active: @spring.active@
  thymeleaf:
    cache: false
    prefix: classpath*:/templates/
    suffix: .html
    mode: HTML
  #返回时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
  # Web设置
  web:
    resources:
      add-mappings: true
      static-locations: classpath*:/static/,file:./assets/public/

  messages:
    encoding: utf-8
    basename:


# 忽略url
ignored:
  # 忽略后台鉴权url
  adminAuthUrls:
    - /
    - /upload/**
    - /actuator/**
    - /download/**
    - /static/**
    - /favicon.ico
    - /v3/api-docs/**
    - /swagger
    - /swagger-ui/**
    - /css/*
    - /js/*
    - /druid/**
    - /admin/base/open/**
  # 忽略记录请求日志url
  logUrls:
    - /
    - /**/aid
    - /app/**
    - /css/*
    - /js/*
    - /favicon.ico


# 分布式唯一ID组件
leaf:
  segment:
    # 默认禁用
    enable: false


# 设置日志级别
logging:
  level:
    org.dows: debug